name: Deploy Docker App on EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH and run Docker deployment
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo apt update
          sudo apt install docker.io -y
          docker stop nginx-container || true
          docker rm nginx-container || true
          docker pull vikesh2608/nginx-html
          docker run -d --name nginx-container -p 80:80 vikesh2608/nginx-html
